[[redirects]]
  from = "/About"
  to = "/About"
  status = 301

   from = "/Portfolio"
  to = "/Portfolio"
  status = 301


   from = "/Contact"
  to = "/Contat"
  status = 301

[build]
  command = "npm run build"
  publish = "build"
